version: "3"

services:
  # Elasticsearch
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet

networks:
  esnet:

volumes:
  esdata:
