version: "3"

services:

  # PHP
  php:
    build:
      context: ./services/php
    networks:
      - server
      - database
      - esnet
    volumes:
      - "${PROJECT_ROOT}:/var/www"
      - ./services/php/config/php.ini:/etc/php7/php.ini:ro
    restart: always
    depends_on:
      - mysql

  # MySQL
  mysql:
    image: mysql:latest
    networks:
      - database
    volumes:
      - "data:/var/lib/mysql"
      - "./services/mysql/dump/:/docker-entrypoint-initdb.d"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"

networks:
  server:
  database:
  esnet:

volumes:
  data:
  esdata:
